import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Sidebar de la doc CDR (instance de docs versionnée par année)

const sidebars: SidebarsConfig = {
  cdrSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
